<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Areas\Admin\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Areas\Views\AttributeRouting\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Views\CustomRouting\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Views\DefaultRouting\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Views\Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Views\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Views\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\AttributeRouting\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\CustomRouting\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Areas\Admin\Views\DefaultRouting\Index.cshtml" />
    </ItemGroup>

</Project>
